import xml.etree.ElementTree as ET



class Constants:
    def __init__(self):
        self.OPENCOMMENT = "/*** "
        self.CLOSECOMMENT = " ***/"
        self.DEFINE = "define"
        self.END = ";"
        self.NEWLINE = "\n"
        self.SYMBOL = "symbol"
        self.EXPORTED= "exported"
        self.SPACE = " "
        self.UNDERSCORE = "_"
        self.EQUALS = " = "
        self.WARNING = "THIS FILE IS AUTOGENERATED:DO NOT EDIT"
        self.EXTENSION = ".icf"
        self.SPECIALADRESSES= "Special Adresses"

class Variables:
    storageType = ""
    moduleName = ""
    symbolName = ""
    address = ""
    symbolOrExported = ""
    constantObj=Constants()


def parseStorageTypeName(root, variableObj):
    for storageType in root:
        #print(storageType.tag)
        variableObj.storageType=storageType.tag
        createEmptyLinkerFile(storageType,variableObj)
        appendInLinkerFile(getHeaderWarningString(variableObj),variableObj)
        parseModuleName(storageType, variableObj)


def parseModuleName(storageType, variableObj):
    for moduleName in storageType:
        #print(moduleName.tag)
        variableObj.moduleName=moduleName.tag
        appendInLinkerFile(getModuleNameCommentString(variableObj),variableObj)
        parseSymbolName(moduleName, variableObj)
        appendInLinkerFile(variableObj.constantObj.NEWLINE,variableObj)

def parseSymbolName(moduleName, variableObj):
    for symbolName in moduleName:
        #print(symbolName.tag)
        #print(moduleName.find(symbolName.tag).text)
        variableObj.symbolName=symbolName.tag
        variableObj.address=moduleName.find(symbolName.tag).text
        setSymbolOrExportedVariable(symbolName,variableObj)
        appendInLinkerFile(getModuleLineString(variableObj),variableObj)
        #parseSymbolOrExported(symbolName, variableObj)


def setSymbolOrExportedVariable(symbolName,variableObj):
    if(isExportedInNode(symbolName,variableObj)):
        variableObj.symbolOrExported = variableObj.constantObj.EXPORTED+variableObj.constantObj.SPACE+variableObj.constantObj.SYMBOL
    else:
        variableObj.symbolOrExported =variableObj.constantObj.SYMBOL

#------------------------------------------to check if <exported> tag exists----------------------------------------------------#
def isExportedInNode(symbolName,variableObj):
    if(list(symbolName)):
        if(symbolName.find(variableObj.constantObj.EXPORTED).tag == variableObj.constantObj.EXPORTED):
            return True
    return False


def getHeaderWarningString(variableObj):
    line = variableObj.constantObj.OPENCOMMENT + variableObj.constantObj.WARNING + variableObj.constantObj.CLOSECOMMENT + variableObj.constantObj.NEWLINE
    return line


def getModuleNameCommentString(variableObj):
    if(variableObj.moduleName!= 'Special_Adresses'):
        line = variableObj.constantObj.OPENCOMMENT+variableObj.moduleName+variableObj.constantObj.CLOSECOMMENT+variableObj.constantObj.NEWLINE
    else:
        line = variableObj.constantObj.OPENCOMMENT+variableObj.constantObj.SPECIALADRESSES+variableObj.constantObj.CLOSECOMMENT+variableObj.constantObj.NEWLINE
    return line


def getModuleLineString(variableObj):
    if(variableObj.moduleName!= 'Special_Adresses'):
        line= variableObj.constantObj.DEFINE + variableObj.constantObj.SPACE + variableObj.symbolOrExported + variableObj.constantObj.SPACE + variableObj.constantObj.UNDERSCORE + variableObj.storageType + variableObj.constantObj.UNDERSCORE + variableObj.symbolName + variableObj.constantObj.UNDERSCORE + variableObj.moduleName + variableObj.constantObj.EQUALS + variableObj.address + variableObj.constantObj.END + variableObj.constantObj.NEWLINE
    else:
        line= variableObj.constantObj.DEFINE + variableObj.constantObj.SPACE + variableObj.symbolOrExported + variableObj.constantObj.SPACE + variableObj.constantObj.UNDERSCORE + variableObj.storageType + variableObj.constantObj.UNDERSCORE + variableObj.symbolName + variableObj.constantObj.EQUALS + variableObj.address + variableObj.constantObj.END + variableObj.constantObj.NEWLINE
    return line


#---------------------------To empty the existing linker file and create linker file if it doesn't exists-------------------------#
def createEmptyLinkerFile(storageType,variableObj):
    path = variableObj.storageType + variableObj.constantObj.EXTENSION
    outfile=open(path,'w')

#--------------------------------------------To append data in linker file------------------------------------------------------#
def appendInLinkerFile(currentLine,variableObj):
    path = variableObj.storageType + variableObj.constantObj.EXTENSION
    outfile=open(path,'a')
    outfile.write(currentLine)


def main():
    infile=open("Data.xml","r")
    root = ET.fromstring(infile.read())
    variableObj = Variables()    #Creating object of Variables Class
    parseStorageTypeName(root,variableObj)


if __name__ == "__main__":
    main()

#end of program
